function importfile(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read
fileToRead1  = 'E:\OneDrive - National University of Sciences & Technology\6th Semester\Digital Signal Processing\Project\825_2_PD_REST.mat'
%  Auto-generated by MATLAB on 12-May-2024 11:36:50

% Import the file
newData1 = load('-mat', fileToRead1);

% Create new variables in the base workspace from those fields.
vars = fieldnames(newData1);
for i = 1:length(vars)
    assignin('base', vars{i}, newData1.(vars{i}));
end

